### PR TITLE
added proximity sensor

### PR DESCRIPTION
**Pull request by watakandai**
added
- adafruit library to `requirements.txt`
- example for reading and plotting

### CODE REVIEW

**Comment by krishnachaitanya7** [comment]
LGTM. @watakandai did you merge it? It's still open? Shall we merge it?

**Comment by watakandai** [comment]
Yeah, it is still not merged.

**Comment by krishnachaitanya7** [comment]
It doesn't conflict with any files I changed. I will go ahead and merge them. Thanks!

**Comment by krishnachaitanya7** [comment]
I crosschecked one file, it seems it has merged without any problems. Everything is good I guess.

**Pull request merged**
