### PR TITLE
Pylint fix

### PR DESCRIPTION
**Pull request by peasant98**
Made a bunch of formatting changes, got rid/commented out unnecessary imports, changed the pylint command to ignore `conf.py` (which is used for the documentation site, and should be ignored), and some other brief changes. Now, pylint is not failing. Issue #34

### CODE REVIEW

**Comment by peasant98** [comment]
also, check to make sure that I didn't break any of the functionality of the code. The functionality should stay the same, but lmk if there is an issue.

**Comment by krishnachaitanya7** [comment]
I see some more rules added to the pylintrc, Would it be possible not to add extra rules? Because if we add extra rules means we are ignoring the Pythonic way of writing. Lemme know.

**Comment by krishnachaitanya7** [comment]
Unless we can prove that the rules are nearly waste, and ignoring them makes sense sometimes

**Comment by krishnachaitanya7** [comment]
Like R1705: Unless you follow Mozilla style of coding, Which I don't for making code more clear

**Comment by krishnachaitanya7** [comment]
After our discussion, I think except one or two rules, I am fine with the rest of them. Thank you for bringing the rating to 10. Atleast from now on, no merging until all tests are passed. That we can all agree on.

**Comment by krishnachaitanya7** [comment]
Also this is a large PR, gimme time till Sunday I guess. Don't have the ADXL wired to breadboard. Need to find a way to test all code, or either remove some files, which are not being used

**Comment by peasant98** [comment]
Thanks @krishnachaitanya9 !

**Comment by krishnachaitanya7** [comment]
I re-ran the linting tests. See this 
image
The naming style should be same across different people, that's why remove C0103

**Comment by krishnachaitanya7** [comment]
E1101 was suppressed because it couldn't find the const file. But I think E1101 is important to note in some cases if something like that is unknowingly pushed. Also, const is a local file so it should look it up. Maybe a different way of running pylint so that it knows where all the files are rather than wildcards? lemme know

**Comment by krishnachaitanya7** [comment]
The const file has to ignore warning like R0902 R0903, because there will be many class attributes and too few public methods, that's how we intend it to be. I think we need to ignore some files from pylint, and then separately run pylint ignoring the special warnings like this also keeping in mind that these rules being ignored should be justified in the docstring so as to why is this even ignored. Lemme know

**Comment by krishnachaitanya7** [comment]
W0105 shouldn't be ignored. If you look into why this error is even being caused, the file adxl335, the docstring is written after calling super. Which is wrong. Please remove it. Maybe you can write the super call below and then push the changes. I think W0105 is good and shouldn't be ignored. Lemme know.

**Comment by krishnachaitanya7** [comment]
Except these 5 I don't see any problem with ignoring the rest as I feel they are legitimate. If you agree can you please make changes and push? I guess don't worry about the score, because those can be fixed. Only naming issue renaming can be a problem. So we would be forced to delete some not-in-use files permanently which is a good thing. Thank you. Great job on finding some extra warnings which can be safely ignored!

**Comment by krishnachaitanya7** [comment]
@peasant98 after you push the changes, @watakandai shall we all 3 (you, me and matt) schedule meeting for a half-hour to remove all these errors? Lemme know

**Comment by krishnachaitanya7** [comment]
That's good!

**Review by watakandai — APPROVED** [review]

**Pull request merged**
